name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

defaults:
  run:
    # shell: micromamba-shell {0}
    # shell: $MAMBA_EXE run -r $MAMBA_ROOT_PREFIX -n $MAMBA_DEFAULT_ENV bash -eo pipefail {0}
    # shell: micromamba-shell 'bash -elo {0}'
    # shell: ./scripty {0}
    shell: /home/runner/micromamba/envs/meh/bin/bash -elo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Python
        uses: mamba-org/setup-micromamba@v2
        with:
          cache-environment: true
          post-cleanup: 'all'
          environment-name: meh
          init-shell: bash
          create-args: >-
            bash

      - name: which bash
        if: always()
        run: command -v bash || true

      - name: shell
        if: always()
        run: echo $SHELL; echo $-

      - name: false
        if: always()
        run: false

      - name: pipefail
        if: always()
        run: false | true

      - name: undefined
        if: always()
        run: echo $HOME_FOO
