name: test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

defaults:
  run:
    shell: micromamba-shell /usr/bin/env bash -elo pipefail {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Python
        uses: mamba-org/setup-micromamba@v2
        with:
          generate-run-shell: true
          cache-environment: true
          post-cleanup: 'all'
          environment-name: meh
          create-args: >-
            bash

      - name: which bash
        run: command -v bash || true

      - name: shell
        run: echo $SHELL; echo $-

      - name: false
        run: false

      - name: pipefail
        if: always()
        run: false | true

      - name: undefined
        if: always()
        run: echo $HOME_FOO
